### PR TITLE
make dev build possible on windows

### PR DESCRIPTION
**Pull request by drblaui**
## Explanation 
Windows has neither the `source` command, nor the `$VARIABLE` syntax for setting and getting environment variables. 

Instead, Windows users can create a `.bat`file (see `setenv.bat`) that utilizes the `set VARIABLE=VALUE` Keyword to set all environment variables automatically. After that the `%VARIABLE%` syntax is used to retrieve those variables 

There is literally no better way to do this on Windows 

## Changes made 
- Provide .bat 
- add new npm scripts `dev:win` and `generate-supabase-types:win`

### CODE REVIEW

**Comment by leandertolksdorf** [comment]
NextJS handles environment variables automatically. Have you checked? https://nextjs.org/docs/basic-features/environment-variables

**Comment by leandertolksdorf** [comment]
Also I changed the target branch to development, as merging into main would redeploy the live app.

**Comment by drblaui** [comment]
> NextJS handles environment variables automatically. Have you checked? https://nextjs.org/docs/basic-features/environment-variables

Using the environment variables in Code won't be a problem, yes. However at the point of generating the types, these variables won't be set anywhere (at least not in windows). Which is probably also why you used the source command

**Comment by leandertolksdorf** [comment]
The setenv.bat is missing :)

**Comment by drblaui** [comment]
> The setenv.bat is missing :)

My bad, forgot to `git add`

**Pull request merged**
